### ISSUE TITLE
Eligibility and character reports

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#1071]
The eligibility and character reports are not showing anything on exercises. For something like Recorder 00033 there must be someone with an eligibility issue so there must be a bug there.

**Comment by warrensearle** [comment]
Re-opened as think this was closed by accident. The bug still appears to exist on production.

**Comment by warrensearle** [comment]
Eligibility Issues has been updated and is now working.
Character Information has been changed considerably as part of apply#563 so the Character Issues report will be updated as part of [TBC]

**Comment by KateMJAC** [comment]
We are receiving reports that elibility issues are still not being flagged by the platform.

**Comment by KateMJAC** [comment]
Assigned to Drie in March WO.

**Comment by KateMJAC** [comment]
Hello Warren, is there an update on this ticket?

**Comment by warrensearle** [comment]
The fix for Eligibility Issues has been included in PR #1332 which has been tested and closed. Part of that testing included checking that the Eligibility Issues report shows up correctly therefore this ticket can be closed from the point of view of Eligibility Issues report.

Work is happening on the Character Issues report under ticket #1139. This will ensure the report displays correctly and includes the fix here... which is simply to ensure the the UI is looking at `applicationRecords` rather than `applications` collection.

In all this ticket can be closed as it has been implemented (plus superseded by another ticket).
