### ISSUE TITLE
Exports should be prepared server-side

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#1100]
Currently we have a number of 'Export to XLSX' buttons in admin and these are all downloading full data to the client and then transforming it into the desired XLSX format. This is clunky. Instead we should be doing this on the server-side and perhaps saving the data to Google Drive as a Google Sheet instead of allowing a direct download.

**Comment by KateMJAC** [comment]
Assigned to Halcyon in the March WO.

**Comment by HalcyonJAC** [comment]
[]

**Comment by HalcyonJAC** [comment]
There appear to be a number of pages with _Export XYZ_ buttons on them that use the existing client-side `downloadXLSX()` function, which need moving to a server-side implementation:

- [ ] Exercises
- [ ] Applications - Export Contacts
- [ ] Reports - Diversity Report
- [ ] Reports - Handover
- [ ] Reports - Outreach
- [ ] Reports - Reasonable Adjustments
- [ ] Reports - Qualifying Test Report
- [ ] Qualifying Tests - Responses

Please confim that the above list is correct

**Comment by warrensearle** [comment]
Hi @HalcyonJAC the following pages are the ones to optimise:
- [ ] Applications - Export Contacts
- [ ] Reports - Handover
- [ ] Reports - Reasonable Adjustments
- [ ] Qualifying Tests - Responses

The following, mentioned above, are all ok as the data being converted to xlsx is already pre-generated or created server-side:
- Exercises _a cloud function does the heavy lifting here. NB this is also being worked on this month_
- Reports - Diversity Report _report is pre-generated via a cloud function_
- Reports - Outreach _report is pre-generated via a cloud function_
- Reports - Qualifying Test Report _report is pre-generated via a cloud function_

**Comment by warrensearle** [comment]
For now I think let's keep them as xlsx downloads.
We can consider exporting to google drive in a future ticket.

**Comment by HalcyonJAC** [comment]
Thanks @warrensearle !

**Comment by KateMJAC** [comment]
Please leave for my return on 22/03 for testing and approval for release.

**Comment by KateMJAC** [comment]
@HalcyonJAC @JeremykJAC I have tested this and found the following: 

•  Applications - Export Contacts: I was able to export the contacts. There was no refresh button, but i'm guessing that was because it doesn't fall under reports? as is the case with QT - Responses. 

•   Reports – Handover: Refresh button was there and I was able to download the report. 

•   Reports - Reasonable Adjustments: Refresh button was there and I was able to download, however the report listed two people within it, while the platform only listed one candidate as having reasonable adjustments (pictures below). 

•   Qualifying Tests – Responses: Was able to dowload the responses. There was no refresh button - as above for applications - Export Contacts.  

![1. RA platform list.png](https://images.zenhubusercontent.com/5fcfacf3d4e677f3af4fdecb/aa4a5924-3cfe-4eb1-823d-ff383f7c8e5b)

![2. RA download.png](https://images.zenhubusercontent.com/5fcfacf3d4e677f3af4fdecb/1a06edfc-7d7c-404b-9c63-eb73c5d8cc3d)

**Comment by HalcyonJAC** [comment]
Hi @KateMJAC 

I have spent some time today trying to replicate the problem you found with the Reasonable Adjustments report, on my workstation but have not managed to. This is could be down to my lack of knowledge on the lifecycle of an exercise and system workflow. I would have called one of the developers for help but didn't want to take much of their time up.

In any case I have some changes to the exports so that the export button is no longer enabled unless there is actually data to export at least, to avoid other possible errors. 

I will speak to one of the dev team tomorrow and see if they can help me replicate this problem locally so I can get to the bottom of it.

Darrel

**Comment by KateMJAC** [comment]
Positive result during testing by Tester User Group. I also tested with a positive result. This can move to reviewed,
