### ISSUE TITLE
Generate Files & Copy to Folder Structure 

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1132]
- As an admin, at different stages of the exercise, I need to generate files relating to selected candidates and copy them into a defined file structure within a designated folder on the JAC's Google Drive. 

**Generating files and documents**

- I need to provide panellists with various documents and written information provided as part of a candidates’ application on the platform, so they can assess it or review it prior to selection days. The information I need to provide panellists includes: 

1.	The panel pack: https://admin-staging.judicialappointments.digital/exercises/5YbFGOQ8TagXkO4RZfEO/application/VcvlNysWH0GsGtnOtHx6#panel
2.	The independent assessments that were sent in (these will be in independent assessments - tasks). There are normally two but there may only be one. 
3.	Anything the candidate had to upload such as a self-assessment, CV, statement of suitability etc. These appear at the bottom of the panel pack as attachments but need to be added to the folder as well. There could be more than one document and they will need to appear separately. 
4.	An export list of selected candidates in Google Sheet format so that panellists can record grades and scores allocated. An example of this will be provided. 

- I need the documents listed above to be named as:  

1)	Application 
2)	Independent Assessment 1 and/or Independent Assessment 2
3)	Replicate what the file is called on the platform
4)	Score Sheet

- The Panel Pack listed at 1) above needs to be updated so that they are all in Arial, font size 11 and all the headings are in bold. The independent assessor details must be removed from the panel pack content. These details are not required in the pack as they get the full assessments to read.

- Once panels have been created and panellists, and candidates have been assigned I need a button within the ‘Panels’ area to export a full panel pack, including the contents listed in the four points above, onto a designated Google Drive.

**Folder Structure**

- I need an area in admin (possibly in vacancy information) where I can allocate a Google Drive for the exercise. I should have already created a Google Drive folder for the exercise before reaching this step.  

- As panels are created on the platform for the exercise and panel members and candidates are assigned, I need a folder created on the exercise’s Google Drive, replicating the structure and naming conventions on the platform: 

1)	Panel folders: Panel 1, Panel 2, Panel 3 etc
2)	Panellists’ subfolders: Chair: Joe Blogs, Judicial: Judge Khan etc
3)	Candidates’ subfolder: These can be name blind using using the characters that appear after the dash within their unique identifier. Eg, if their unique identifier is JAC00351-fiz0003 we need to use fiz0003. For selection days I will need the folder name to be the candidates full name. 

- I need the files and documents listed above to be exported to the corresponding candidates’ subfolder. 

- I need the candidate subfolders to be replicated in the folder of each panellist they are assigned to, so that panellists can make independent notes and comments on the content within the folders.  

- I will keep record of the scores confirmed within the score sheet completed by the Chair of each panel. In the future I may need to import the data within this score sheet on Google Drive back onto the platform, so I require functionality to enable this to happen if possible.

**Comment by KateMJAC** [comment]
@lloback @warrensearle I have a few queries off the back of Design Group and Digital Drop-in meetings:

Selection day panel packs will need to include a candidate’s sift report, which is created and saved on Google Drive and not on the platform. The sift report will need to be located with the rest of the panel pack documentation that is exported from the platform. Could a single document be saved in the candidate’s folder with the exported files or is the only option to copy the folders to another location on GD and then drop the additional document within the candidate’s folder?

What file types will the documents exported from the platform be in? we need these to be in formats that allow panel members to make notes and edit, so not PDF. 

It would be preferred if panel members could be given access at the point the folder is created, so that Ops team members don’t have to allocate time to do this. 

There is also a preference that the Google Drive folder is created on behalf of the team when the files are exported, rather than teams creating a folder and entering a Google Drive link while creating a panel.  

Happy to discuss on Monday.

**Comment by warrensearle** [comment]
Here's our progress update for the essentials of this task:
- [x] Create Folders and sub-folders
- [x] Create google docs
- [x] Create google sheets
- [x] Create panel pack view of application as google doc
- [x] Copy files from Cloud Storage to Google Drive
- [ ] Create Folder tree from Panels and Panelists
- [ ] Assign permissions to Panel and Panelist folders
- [ ] Copy/duplicate candidate folders into Panelist folders (look at Share options)
- [ ] Empty/Delete Folder tree (look at options to preserve additional files added)
- [ ] Cloud function to Export Panel to Google Drive
- [ ] Cloud Function to Export All Panels to Google Drive
- [ ] Speed it up. Currently taking too long to be viable for a large exercise (particularly with duplication)
- [ ] Improve Robustness
- [ ] Read data back in from google sheets
