### ISSUE TITLE
Independent Assessors Unable to Access Links 

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1182]
As an independent assessor (user), I have been unable to use the supplied link, generated by the platform, to provide an indpendent assessment for a candidate in relation to the Recorder 2020 exercise (exercise 033). 

I have used the link in Firefox and Safari browsers and I am still unable to access it. 

I have reported this issue to the selection exercise team (SET) and they are unsure whether it is user area or a bug, as other independent assessors have reported similar issues. 

I have had to email in my assessment to the SET instead of submitting it to the platform. 

I would like to be able to access the link directly and upload my independent assessment directly onto the platform.

**Comment by KateMJAC** [comment]
I am able to provide the name of this assessor and any others, to the developer who pics up this ticket.

**Comment by mbrookeswebdev** [comment]
I've looked into this issue and haven't been able to reproduce the described error, the links worked fine for me. As the candidate didn't provide any information to describe what exactly happened when they clicked on the link, it's hard to say whether they encountered a technical issue or whether they could not access due to some user error, (for example, using copy/paste and missing part of the link etc).
