### ISSUE TITLE
SPIKE: Options to support selection day interview booking

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1200]
In delivering a solution for selection day interview booking functionality we need to balance, user requirements, cost and delivery time. However, ultimately, we are unable to go with a possible solution if key user needs listed in #1199 aren’t met. 

Our starting point should be plug-ins and API solutions. Previous research has been completed in this area, findings of which can be found here:  

https://docs.google.com/document/d/17ZiASyAoXF5T-gdNG_dyold1zAdhvsh69cGWP5pDw3U/edit 
 
A possible Word Press plug-in is Bookly: 

https://www.booking-wp-plugin.com/ 

It may also be worthwhile to look at other available providers or functionality of apps already used by the JAC. 

If we are unable to meet key user needs via the above solutions, then we can focus on prototypes for a build on the JAC’s digital platform.

**Comment by tomlovesgithub** [comment]
![selection days calendar.jpg](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/29c26456-8a41-4611-a8b1-50268be9d6e3)

**Comment by KateMJAC** [comment]
Hello @tomlovesgithub as discussed on Slack, if you can accompany the above with a brief rationale on plugs-in vs platform build and the proposed next steps, I will take it forward to Digital Leaders for discussion. 

Thank you

**Comment by tomlovesgithub** [comment]
**Issue:**
Teams need a booking system to relieve the task of having to assign candidates an interview based off of their availability. 

**Solutions considered:**
There have been a number of off-the-shelf solutions investigated by the SE teams. 
These range in features, cost and integration, however well outline the needs of the teams 
Whilst i did investigate these options i felt they were not able to fully satisfy the requirements.
- There could still be considerable workload in transferring this data onto our platform in order to generate panel packs [either with a digital solution, or a manual effort on behalf of teams].
- We sacrifice the flexibility staff are used to with the building of these features, including things like reasonable adjustments, conflicts may be a considerable effort or perhaps even something we would have to ask the providers for.
- The separation of this feature from the rest of our app has many considerations, and i believe it would be best to as closely integrate this with the current platform as possible.
- As this feature would ideally be integrated into the platform we lose control of downtime, maintenance and bug handling.
This considered i felt that it would not help to effectively relieve the bottleneck and manual efforts of the staff

Platform build - I looked into our existing features to see where best an interview system would fit **into** our platform. 
I talked with selection exercise members about what the MVP and ideal feature would provide, in order to understand where this feature would best fit into our platform. 
- The pros of doing things this way are largely outlined within the cons of using a pre-made system
- This would allow for greater automation around selection days and hopefully a compounding of time saved for teams, as candidates would effectively assign themselves to panels by their own selection of location and date, as opposed to admins having to do.

**Suggested action:**
Creating booking functionality on the platform. 
The attached diagram shows the workflows that would enable this build as well as some MVP and further considerations.
