### ISSUE TITLE
S9(1) type exercise functionality (ex 35)

### ISSUE THREAD

**Issue by mbrookeswebdev** [jac-uk/admin#1212]
One of the Selection exercise teams is running an s9(1) exercise that uses 1x Leadership Judge per candidate, as opposed to 2x Independent Assessors. It is the first time S9(1) Exercise is been done on the Platform.  The  IA's  are mandatory Fields on the platform. What can be done to remove IA requirement from this exercise?

The exercise (JAC0035) has been created on the platform and it will be launching on 17th March and any solution will have to done and tested by the 16th before the exercise launches.

We require a short-term solution to cover exercise 35 and a change to cover all future s9(1) exercises.

**Comment by mbrookeswebdev** [comment]
Given the short time available for implementation and testing before the exercise 35 goes live we could: 

1. Conditionally for exercise 35 modify IA route and request leadership judge details instead of IAs. (See [spike branch on Apply](https://github.com/jac-uk/apply/compare/ex35-ia-change), [spike branch on Admin](https://github.com/jac-uk/admin/compare/ex35-ia-change))

2. Conditionally hide IA form and functionality on Admin side of the platform and display Leadership Judge details with understanding that, until the full required functionality is understood and recorded, this information will be managed manually by team members.

Some screenshots from Apply/Admin:

![LJ1.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/f5557474-5613-4c84-99bd-cbf7e39f8ad8)
![LJ2.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/63dbfa35-61d8-47eb-b75e-42892c92f8b5)![LJ3.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/bd3de174-b24a-43c3-b59f-5c027c3daa3e)![LJ4.png](https://images.zenhubusercontent.com/5f719a59e2ae0739a5c9b6e0/a6f77152-f32f-4840-b6a2-633b0fc977a6)

Long-term solution - we need more details, to understand fully how s9(1) exercises are different from other types and where information collected from candidates will be used on the Admin side of the platform (i.e. reports, exports etc)

**Comment by warrensearle** [comment]
The following changes have been implemented:

**Admin**
 - [ ] Exercise > Assessment Options > Update. Include two new checkboxes for 'Independent Assessments' and 'Leadership Judge Assessment'
- [ ] Exercise side navigation. Exclude 'Tasks > Independent Assessments' if it has been turned off (using above form)
- [ ] Application. Show **Independent assessor details** and **Leadership judge details** when relevant
- [ ] Application. New modal to add/edit Leadership judge details

**Digital Platform**
- [ ] Copy new `assessmentMethods` field from `Exercises` documents to `Vacancies` documents

**Apply**
- [ ] Task list. Exclude 'Independent Assessments' if it has been turned off
- [ ] Task list. Include 'Leadership Judge details' if relevant
- [ ] Task list. Review button. Update logic so Leadership Judge details are required to enable the button (if relevant)
- [ ] Leadership Judge details. New form to add/edit Leadership Judge details
- [ ] Review. Exclude 'Independent Assessments' if it has been turned off
- [ ] Review. Include 'Leadership Judge details' if relevant
- [ ] Review. Send application button. Update logic so Leadership Judge details are required to enable the button (if relevant)

**Comment by KateMJAC** [comment]
@warrensearle I have tested this and have found the following: 

On Admin Staging:

- [X]  In the ‘Exercise > Assessment Options > Update’ you will notice two new checkboxes for 'Independent Assessments' and 'Leadership Judge Assessment

- [X] In the Exercise side navigation ‘Tasks > Independent Assessments’ will be excluded (it has been turned off using the above form)

- [X] In ‘Applications’ candidates’ information will include Leadership Judge details (it has been turned on using the above form).

On Apply Staging: 

- [X] Notice that Independent Assessor are no longer requested 

- [X] Notice that Leadership Judge details are requested

- [X] Complete and submit application
  
**Issues:** 

- In Admin, when selected 'Leadership Judge Assessment' in 'Assessment Options', the IA dates question still remained on the 'Timeline' page. This may create confusion for SETs and if not completed may also not allow that exercise to be 'Approved', so that processing can occur.

- In Admin, when creating the exerice, under 'Assessment Options' I was able to select both 'Independent Assessments' and 'Leadership Judge Assessments'. This resulted in the Apply side including both ‘Independent Assessors’ details and ‘Leadership Judge Details’ questions under ‘Assessents’ (section 3) of the application form. Users should be made to choose one or the other on admin side, so that both options can be present on apply. 

- In Admin, to approve the exercise on the platform I had to upload an attachement for indpendent assessment in the 'Download' section. 

- In Admin,when I approve the exercise and then select 'Assessment Options' from the 'Exercise' side naivgaton it displays 'None' 


Further user testing needs to occur before this can go live. I will be chasing SETs to complete this.

**Comment by warrensearle** [comment]
Thanks @KateMJAC based on the above issues will work through the following tasks:
- [ ] Admin. When Independent Assessments option has been turned off. Remove IAs from timeline edit & view pages.
- [ ] Apply. When Independent Assessments option has been turned off. Remove IAs from timeline view.
- [ ] Admin. When Independent Assessments option has been turned off. Remove IAs from exercise downloads page.

I have the following questions:
1. Can we work on the Assessment Options view page - e.g. getting it to show more than 'None' - as part of the follow up work to make Assessment Options more modular [ ticket TBC ]?
2. Could an exercise want Leadership Judge Assessment **and** Independent Assessments? It's been built so that these could co-exist. Yes we can make them mutually exclusive if you want, just wanted to point out that there's no technical need to do this. For now could this also be left until the work to make Assessment Options more modular?

**Comment by KateMJAC** [comment]
@warrensearle - Answers to your questions.

1) Yes we can, but at the moment it may be a little confusing. Can we put another messag there like 'under developement' or something to indicate that is isn't an error?

2) I don't believe that an exercise could have both Leadership Judge Assessment and Independent Assessments, but that's not a definitive no. My concern is that a user would choose both in error. However an SEO is required to review an application before it is published, so this should be picked up. Lets leave it for now and when the functionality is rolled out, i'll demo with a big reminder not to choose both. 

If you can let me know when the other three points are completed, I can get the user testing group to have a look. 

Looking at 035's launch data on the website it lists 31 March. I'm chasing this up with the exercise team to confirm.
