### ISSUE TITLE
Scenario QT Test Timer Issue

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1240]
****High priotrity - this issue needs to be resolved and another external volunteer dry run completed by COB 12 April for the dry run taking place on 13 April.** 

**The issue:**

During the 051 scenario QT dry run that took place on 24/3/21, an issue regarding the timer was identified. 

The time allowed for the test was 60mins. Two candidates were marked as DNF (candidate names contained in the email provided). For these two candidates the timer recorded a time beyond 60mins. 

Candidate 1: advised that “the test stopped unexpectedly just before I ran out of time without submitting my answer to the second question.  I thought that I had about a minute left, but the red stripe at the screen suddenly disappeared and then when I tried to submit my answer it said that time had expired”. They time taken on the test recorded as 7:26:59 hrs.

Candidate 2: Had a test time of 1:36:53 recorded. 

Please find further detail and candidate names in the email sent on 29/03/21.

**Describe the solution you'd like:** 

We would like the issues investigated to confirm whether it is far reaching, or whether this was an isolated incident, and any required issues addressed. 

This issue needs to be resolved and another external volunteer dry run completed by COB 12 April for the 2nd dry run taking place on 13 April.

**Comment by warrensearle** [comment]
We have investigated and there are two issues here:

**Close & Score**
When a test has finished and the “Close & Score” button is pressed. It updates all ‘in progress’ tests as 'completed' and sets their completed timestamp as the end time of the QT. This is fine for tests that are actually in progress however there are two other scenarios which are not being sufficiently catered for:
 - A candidate may 'Exit' their test and then not come back to submit it
 - A candidate may simply close their browser rather than submitting their test
In both cases their test will remain 'in progress' until "Close & Score" updates it. However setting the completed timestamp to the end of the QT leads to misleading test durations being reported.

Instead for the above scenarios we should:
1. Apply. Store the timestamp when a candidate exits their test - e.g. `exitedTest`. N.B. they need to be able to resume their test again (if in time)
2. Digital Platform. During ‘Close & Score’ set the `statusLog.completed` timestamp to one of the following rather than QT endDate:
  - `exitedTest` if we have a timestamp stored for when the candidate exited the test
  - `statusLog.started + duration` if we don't have an `exitedTest` timestamp
3. Digital Platform. Mark these candidates as DNF (`isOutOfTime = true`) and perhaps capture an additional flag to indicate Exited Test or Estimated Completion, as appropriate

**Browser support**
A small number of candidates are reporting being ejected from the test sooner than expected. In one case (using Microsoft Surface Pro & Edge browser) the candidate was ejected as soon as they started the test! 
We haven’t been able to replicate this however we should work on the following areas:
- Capture browser, platform and environment (including clock & timezone) information for each candidate taking the test
- Browser testing. Test our UI on more platforms & browsers, perhaps using BrowserStack or similar to identify any incompatibilities
