### ISSUE TITLE
Character issues Export button

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1319]
As an admin l want to click on export data button so that l can download the character report.![Capture.PNG 25.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/5d62337c-eafd-436f-ad0c-2e59399abeb2)

Note: The team have to click on character issue underneath report. To get the information they need they have to click on each candidate that is under character issues and copy and paste the data in a spreadsheet.

Building the export data button will allow the team to have all the data they need in a spreadsheet and reduce human error.

**Comment by joy-ade** [comment]
@JeremyJAC l will email you the report.

**Comment by JeremykJAC** [comment]
@HalcyonJAC  Tom, the report for this issue is within our internal JAC channel.

**Comment by warrensearle** [comment]
During testing we identified the following changes are needed:

1. Rename the cloud function `generateCharacterCheckReport` to `exportCharacterIssues`
2. Ensure `exportCharacterIssues` function looks at `applicationRecords` rather than `applications` collection
3. Update Admin UI to look at `applicationRecords` instead of `applications`

**Comment by HalcyonJAC** [comment]
Out of the things that @warrensearle identified above, items 1 and 3 have been done as part of this ticket. Item 2 will be done in ticket #1139
