### ISSUE TITLE
Virus scanning improvements

### ISSUE THREAD

**Issue by KateMJAC** [jac-uk/admin#1393]
The original virus scanning work was carried out in #221, now we'd like to complete the following tasks: 

- [ ] Allow one instance of the app to scan develop, staging and production (i.e. so that we only need one instance running 24/7 still, but can cater for all 3 environment).
- [x] Resolve the existing deployment problem so that ClamAV service does not have to be started manually during deployment.

**Comment by HalcyonJAC** [comment]
This took quite a while for me to diagnose but ultimately the problem is caused by the fact that the `/var/run/clamav` folder is owned by `root` and `freshclam` runs as a user called `clamav`.

So, I added a line to the deployment script to change the owner of the `/var/run/clamav` to be the `clamav` user.

**Comment by andrew-isaac** [comment]
Virus scanner doesn’t look like it is effected by the log4j vulnerability however we do need to get it updated to use the latest version: currently it is using v1.0.0 whereas the latest is v1.7.0

**Comment by andrew-isaac** [comment]
@JeremykJAC  - I have added the new information here

**Comment by HalcyonJAC** [comment]
It turns out the the above warning wasn't causing the problem at all.
