### ISSUE TITLE
PQE Field

### ISSUE THREAD

**Issue by joy-ade** [jac-uk/admin#1517]
**The Why**
All that is required for post qualification experience field is month and year data. Candidates were asked to fill in the month and year data  in the  post qualification experience field. 

Candidate only entered the month and year in PQE field, the platform is including the day in field.  The platform is also displaying the day data  to the (Apply App) candidates when they checked their PQE field in their application.  

The platform is also inputting the day data on PQE field across all exercises on the platform even though the candidates only provided month and year for PQE
![image (13).png](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/57c84a5e-8fbc-42f6-9c3b-25ef82c3bfff)

**Expected**

- Post qualification experience field should only display month and year data  on admin app.
- Post qualification experience field should only display month and year data  on Apply app.

![Capture.PNG131.PNG](https://images.zenhubusercontent.com/5f7b3a91edd7a0a890566450/29394c3c-fff2-4e75-bf81-2b416ba8c495)

**The User Stories**

As an administrator l want the platform to display the month and year  data in the PQE field so that l can view the data that has been inputted by that candidates.

**Comment by warrensearle** [comment]
Have looked into this and it's not as straight-forward as I'd hoped!

The work on #260 is good however there we genericised fields and here we need to 'take back control'!

As things stand date fields are wrapped within a generic component, and then in another, so there are some changes needed to these in order to support month-only dates.

The risk is we over-complicate our generic components and need to take a different approach so end up with hard-to-manage code.

Hence have estimated at 5 SPs!
