### ISSUE TITLE
Automate selection exercise and dummy applicant data on staging

### ISSUE THREAD

**Issue by JeremykJAC** [jac-uk/admin#1580]
**To do**

Create a bank of testing data, from production. 3,000 candidates that will have some of their information obscured, for security (phone number and email address to contain random characters at the end i.e. jeremy123@judicial)
Hold this data in the db to be called upon when needed to fill in an exercise with relevant/real information.

All our test data will have the same login password, but unique email addresses. This will allow us to login as any user on Apply for testing purposes.

**Acceptance criteria** 

**Generate a bank of test data**

- [x] 3,000 records from prod to be stored here xxx 
- [x] Change applicants phone numbers to 08000 000 000
- [x] Add sequential numbers to the end of their email address before the @ i.e. Justin123@, Barbara124@, Lawrence125

- [x] Generate the same password for each applicant (send this to developers in Slack)

**Load test application data** 

- [x] When an exercise is published and approved a Create test applications button will appear

- [x] When this button is selected a pop up appears to select applicant number. Chose between 1-3,000 then test applications will be generated from xxx

- [x] Once successful the Success! button will appear and then move to Process late applications. (this is the usual flow)

**Design** 

Create test applications button

![Create Test Application.png](https://images.zenhubusercontent.com/603ccb08852e7606029cef76/d9762c0e-f72f-4f5b-a663-37834179dc3f)

Choose application number

![Create Test Application enter number.png](https://images.zenhubusercontent.com/603ccb08852e7606029cef76/e0abbfaf-08af-47fa-8cf5-ff633b512ef1)

Success state

![Create Test Application success.png](https://images.zenhubusercontent.com/603ccb08852e7606029cef76/8fed353a-011f-4ec5-9955-919b22275f8f)

Applications table

![Test Data List.png](https://images.zenhubusercontent.com/603ccb08852e7606029cef76/eb8b87a3-584d-4a9c-86c0-624baaff4242)

**Comment by warrensearle** [comment]
We need to go a lot further with cleaning the dummy data. Plus please ensure it is not publicly accessible!

Would suggest at least the following additional steps however please use your own diligence to ensure that no personal or identifiable data is used:
 - [ ] Replace the email addresses with our own dummy ones (rather than appending numbers to existing addresses). e.g. could use Shark Lasers / Mailinator or another dummy email generator (if we need to access emails) or simply a made up domain like `@jac-dummy-email.jac`
 - [ ] Ensure Assessors data is replaced with dummy data
 - [ ] Look to replace character information details with 'lorem ipsum' or similar. In some instances the explanations include fairly sensitive data
 - [ ] Look to replace qualification place names
