### ISSUE TITLE
Diversity Report - EMP Applied on Fields

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#1777]
Exercise 086 DHCJ had EMP applied at the Handover point of the exercise. The team have set the candidates against the correct stage and status and they show in the EMP Applied field but the breakdown basis of ethnicity or gender does not display the breakdown of figures.

Can this be looked into, so the correct figures are showing on the report?

https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/1776
https://admin.judicialappointments.digital/exercise/mvfZbVyM8mTFPqUMIqJV/reports/diversity#handover
![image.png](https://images.zenhubusercontent.com/61df018d45c3e70202f990c8/e7b4a66f-4aac-419d-8f00-4d463c659507)

**Comment by tomlovesgithub** [comment]
I have reviewed the code and the applicationRecords in the database for this exercise and it seems that none of the candidates had EMP applied under either basis.
It is worth noting that the options to set EMP with a basis of ethnicity or gender are found only **when moving a candidate from the selected or shortlisted** stages.
This is likely the issue here and perhaps adding this option to these stages be a decent solution for the future.
However if the team are able to provide a list of candidates who require an EMP basis adding then we can ensure the report on the platform will generate correctly.

Recommended
![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/9a02bb44-058d-473f-bc7c-10d38ee71bb5)

Selected
![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/929a7017-3e10-483f-9432-dc18ed0c77f2)

Shortlisted
![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/eb73e60b-1ce3-49d4-95f7-272ff9045f96)

Review
![image.png](https://images.zenhubusercontent.com/5e9d7da659354ff66af12557/e85c0614-3b23-43c9-9cfd-c5863901fc4a)
