### ISSUE TITLE
Exercise Approval - Help Text - UT Feedback

### ISSUE THREAD

**Issue by andrew-isaac** [jac-uk/admin#2012]
Explore option for condensing down the pop up message for Admin

Do we need three of the same message can it not be condensed to have all 4 in the one message or have the message and then the 4 teams listed underneath?

![Image](https://user-images.githubusercontent.com/97609636/213428057-470b2b6a-1fac-403d-abca-df4d64bef3fe.png)

**Comment by warrensearle** [comment]
Please make this a series of check boxes, as follows, so that all check boxes need to be ticked before the Submit button becomes enabled:

**Submit for Approval**
Please make sure the information and application form (if relevant) has been cleared by all of the following:
[ ] JAC Policy and Diversity Teams
[ ] JAC Digital Team
[ ] Head of Operations and Digital
[Cancel] [Submit for Approval]
