### ISSUE TITLE
Outreach report

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#2097]
We currently ask candidates in the application where they heard about the role to aid future outreach. This information is pulled across into an outreach report for each exercise. Additionally, as part of the diversity monitoring form we ask candidates whether they have attended an outreach event, participated in the Pre-application Judicial Education Programme or engaged in judicial shadowing. It would be beneficial to have all of this information in one place and to, therefore, add the additional fields from the diversity monitoring form to the outreach report on the platform.

As of 21st Sep:
In addition, the declaration rate on the report is currently listed amongst the outreach options. At the top of the report is a grey box showing the 'Total applications'. Could the grey box also include the declaration rate?

**Comment by nickaddy** [comment]
Omar to pick up when he returns

**Comment by drieJAC** [comment]
I am going to refactor the DP function to reduce the memory usage by selecting only the fields we need and also using the _processing field in applications instead of having to get data from the applicationRecords.
Then we can reduce the amount of memory allocated to the function back down from 512MB to 256MB (after testing on develop vs 5000+ applications).
