### ISSUE TITLE
Update Application view on Admin

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2167]
**Background**
The application form has been updated for the candidate on the Apply side; the application view on Admin needs to be updated accordingly.

**User Story** 
As a user, I would like the changes to the candidate application to be reflected on Admin so that I can assess the candidates' relevant work experience and suitability for the role.

**Description** 
The admin application view must align with the new structure of the application form on Apply.
**This work must only apply to _applicationVersion 3.**

**User Testing Steps**
TBC

**Comment by warrensearle** [comment]
@nickaddy 
Please confirm that we need to support editing work history in Admin. I'm pretty sure we would need to but it's worth asking.
Also whether we should do so under this ticket or move "Allow JAC to edit candidate work history" to a separate ticket?

**Comment by nickaddy** [comment]
@warrensearle Don't quite grasp this, what editing would Admin want to do in the work history?

**Comment by warrensearle** [comment]
Hey @nickaddy 
In application view the team can press the Edit button in order to edit all fields in the application.
I guess one use case for having this functionality is where the team might enter the data on behalf of the candidate, say because of a reasonable adjustment or a technical glitch.

Here's what it currently looks like:
<img width="646" alt="image" src="https://github.com/jac-uk/admin/assets/8524401/62b05e9e-2207-4bed-a11a-742ca9f3c1e3">

Note we are using components to enable each field to be individually editable so this isn't a massive piece of work to roll out to the new Work History fields. Just thought it was worth calling out to double-check we do still want to support this functionality and whether it has the same priority as everything else.

**Comment by warrensearle** [comment]
Okey dokey we will size it to cover View & Edit functionality

**Comment by HalcyonJAC** [comment]
Note: 

1. Not sure how we manage the items when setting up the application process of an exercise.
    - Post-qualification work experience
    - Judicial experience
    - Gaps in employment

    ![image](https://github.com/jac-uk/admin/assets/79906532/ed072260-49f1-4dfd-9863-dd913d607399)

**Comment by warrensearle** [comment]
@HalcyonJAC for exercises that use the current/old application form they will have the existing three forms for Post-qualification work experience, Judicial experience and Gaps in employment. In the new application form these have been replaced by one form ('Work history' is it called?).

So for exercises with `._applicationVersion` field set to 2 or less then we show the three current/old forms here and for exercises which use the new application form (where `._applicationVersion` is 3 or more) then we should have just one form here.

(might be easier to speak rather than type this out)
