### ISSUE TITLE
Facilitate completion of full application in staged exercises

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2515]
## Background
In exercise JAC00184, an issue arose due to the second stage not being aligned with the new stages & statuses introduced earlier this year. That issue was resolved, but it also became apparent that it was not easy for Admins to see when a candidate had completed the second part of their application. Hence, we would like the platform to show when a candidate has completed their full application. The focus here is on supporting Admins on JAC00203, for which the second application stage will take place in November and the aim is to provide a partial, stop-gap solution, whilst reviewing the overall staged process in slower time.

Notes:
1. In staged applications, candidates can update their application as many times as they wish within the window. 
2. The status 'Full application not submitted' already exists and would be applied by Admins to candidates that did not complete their application at the second step 

## User Story
As an Admin, I would like to be able to see which candidates on my exercise have completed their full application so that I can send reminders if necessary.

## Feature(s) Description
- [x] Add a new status 'Full application submitted' at the Selection days stage (Admin, DP & Apply)
- [x] When candidates complete all sections requested in the second stage of the application, review their submission and press submit (at least once), record a timestamp in their application document (Apply)
- [x] In onApplicationUpdate check for completed staged applications (look at the new timestamp) and update the corresponding applicationRecord to have the status of 'Full application submitted' (DP)
- [ ] For clarity: the status of candidates that have not completed all sections and hence have not pressed submit at least once remains as it is (probably 'Shortlisting passed')
- [x] Ensure the 'Full application not submitted' status appears in the Selection Days list of statuses that can be assigned and that it is configured to send the application back to the previous stage of Shortlisting (Admin)
- [x]  Include the new status in the filters in Exercise > Stages for Shortlisting and Selection Days (just in case SETs want to view only those candidates who have completed applications) (Admin)
- [x] In onApplicationUpdate send an email (via Notify) when a candidate has submitted their full application

## Acceptance Criteria 
It's done when:
- [ ] Admins can clearly distinguish candidates that have submitted their full application by their status
- [ ] The new candidate status 'Full application submitted' is displayed in the status column on the Stages page
- [ ] The new candidate status 'Full application submitted' is displayed as an optional filter on the Stages page
- [ ] Any candidate given an extension to their application also receives the new status as long as they have clicked submit within the newly specified deadline.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
1. On an example staged exercise with incomplete second stage applications, try to distinguish which candidates have incomplete applications

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2515?planning-poker) with Zenhub @drieJAC @HalcyonJAC @KoWeiJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
@nickaddy can we discuss this one further as I think we need to clarify what we are updating.

We have two documents:
 - `application` contains all the data submitted by the candidate along with their submission status, date and reference number
 - `applicationRecord` contains internal private data and contains their stage & status through the post-application process

We should definitely record when the candidate has submitted their full application in the `application` document.

We can also use the `application` content (or lack of) to identify which applications have been completed and so this can easily be displayed on screen in the applications list & application view.

If we decide to update `applicationRecord` status for completed applications with 'Full application submitted' then we need to think through how this should work. It may necessitate combining Staged Applications and Tasks functionality: potentially a new 'Full applications' task, along the lines of PSDQ, which monitors submissions, allows reminders to be sent and when closed/completed updates the status of applications to 'Full application submitted' & 'Full application not submitted'

There may be a simpler solution (i.e. not another Task!) if we only use the 'Full application not submitted' terminal status and otherwise leave the `applicationRecord` alone.

_Note: I think probably a new Task and simplifying Application Process is the way to go but we should talk it through_

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2515?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2515?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Hi @nickaddy am happy with what we discussed today (08/10/2024) and have estimated accordingly. It says this in the ticket description but just to clarify (hopefully) the tasks involved in implementing this ticket are:

- [ ] Admin, DP & Apply. Include a new status called 'Full application submitted'
- [ ] Apply. When candidate submits a full application (in a staged application), record a timestamp in their `application` document
- [ ] Digital Platform. In `onApplicationUpdate` check for completed staged applications (look at the new timestamp) and update the corresponding `applicationRecord` to have the status of 'Full application submitted'.
- [ ] Admin. Ensure the 'Full application not submitted' status appears in the Selection Days list of statuses that can be assigned and that it is configured to send the application back to the previous stage of Shortlisting.

Some optional additions are:
- [ ] Admin. Include the new status in the filters in Exercise > Stages for Shortlisting and Selection Days (just in case SETs want to view only those candidates who have completed applications)
- [ ] Digital Platform. In `onApplicationUpdate` send an email when a candidate has submitted their full application

**Comment by HalcyonJAC** [comment]
I discussed this with Nick last Friday and we agreed that:
- [x] Release the changes on admin on 18th Nov.
- [ ] Run a script to check how many candidates have submitted the applications for Exercise 203 and update their status to `Full Application Submitted` on 20th Nov.
