### ISSUE TITLE
Create grading sheets as part of panel pack

### ISSUE THREAD

**Issue by nickaddy** [jac-uk/admin#2524]
## Background
To streamline the process for uploading grades, we will want to generate a grading sheet, based on the assessment criteria specified by the Admins in Additional settings and any additional columns added, e.g. ASC, Welsh language etc [as in #2500](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2500). 

## User Story
As an Admin, I would like a grading sheet to be generated based on the assessment criteria and additional columns specified so that it is straightforward for panellists to complete an upload.

## Feature(s) Description

- [ ] Grading sheets for sifts must have a first column of Application reference
- [ ] Grading sheets for sifts must have a column for each competency/skill selected in the set-up (abbreviations shown below), and Overall band column
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02f837f0d10f4bf2884a63bc3e81da910e6f7d03/image.png" alt="image.png" />

- [ ] Grading sheets for sifts must include additional columns - ASC, etc - if specified by the Admin
- [ ] Grading sheets must take into account the panel set-up, i.e. if there are multiple panels, a grading sheet should be generated for each panel including rows for all the candidates allocated to that panel
- [ ] Grading sheets for SDs must have:

-  a column for each competency/skill selected in the set-up (abbreviations shown above) preceded by IV (interview), e.g. IV PBK, IV ACI, etc
-  a column for each competency/skill selected in the set-up (abbreviations shown above) preceded by SQ (situational questions), e.g. SQ L, IF that option has been ticked in the set-up
-  a column for each competency/skill selected in the set-up (abbreviations shown above) preceded by RP (roleplay), e.g. RP ACI, IF that option has been ticked in the set-up
-  a column for each competency/skill selected in the set-up (abbreviations shown above) preceded by SLQ (strategic leadership questions), e.g. SLQ L, IF that option has been ticked in the set-up
-  IF more than one selection tool is used in the SD, e.g. interview and roleplay, there should be a column for each criteria and an overall column for each criteria, e.g. IV EJ, RP EJ, Overall EJ
-  Overall band column
For example:
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ff2bb050b4b8eb32f54ac3458a0711955e403af/image.png" alt="image.png" />

## Acceptance Criteria 
It's done when the grading sheets are generated for panellists as per the criteria specified by the Admins and according to the panel set-up.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2524?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by HalcyonJAC** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/2524?planning-poker) with Zenhub @KoWeiJAC

**Comment by warrensearle** [comment]
@drieJAC let's pair on this ticket!

Just to clarify this is a `digital-platform` task, no UI is needed as part of this ticket. 

In the first iteration (spike) please could you look at creating a Sheet on Google Drive (as part of the panel pack export) and see if you can create fields/columns which restrict what values can be entered (I guess like a dropdown). For example we would like to have columns on the sheet with the following input types:

- Grade (only allow A, B, C or D as input value)
- Yes / No (only allow Yes or No as input value)
- Pass / Fail (only allow Pass or Fail as input value)
- Level (only allow None, Basic, Medium, High as input value)

For the Document we create on google drive we cheat slightly by creating HTML and then converting this to a Google Doc. In this instance I think we'll need to do things properly and use the Drive API (or Sheets API?) so that we can (hopefully) define the input values as described above.

Let me know when you are done with the above as at that point I should have a defined data model for you to use. Essentially there will be an array of `columns` where each column has a `ref` and a `type`, for example:
```
[
  { ref: 'PQE', type: 'grade' },
  { ref: 'Welsh questions', type: 'level' },
]
```
