### ISSUE TITLE
Admin ability to edit candidate applications

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#260]
**Is your feature request related to a problem? Please describe.**
As an Super Admin, I need the ability to edit application information upon request of candidates after a form has been submitted. 

**Describe the solution you'd like**
Essentially being able amend all sections of the application, from 'Character information' down.  

The change option we have on 'Personal deatils' should be across all fields in the application. 

If these details are changed, changes need to be reflected in all areas where the data is held. 

Once work to log actions is complete, this feature can be opened up to all admin users.

**Comment by warrensearle** [comment]
This is not especially complex but is quite a large piece of work to bring into Admin. It is not achievable to implement, test and deliver by the deadline of 17th Feb.

Potentially we could enable the admin team to log in to the Apply app and impersonate a chosen user. There are benefits here in that Admin will experience the exact same interface as the Candidate. It should also be slightly quicker to implement however would require care, attention to detail and thorough testing due to the risk involved. Right now we are locked down so an application can only be edited by the candidate who made the application.

**Comment by ClaireTroughtonJAC** [comment]
> 
> 
> This is not especially complex but is quite a large piece of work to bring into Admin. It is not achievable to implement, test and deliver by the deadline of 17th Feb.
> 
> Potentially we could enable the admin team to log in to the Apply app and impersonate a chosen user. There are benefits here in that Admin will experience the exact same interface as the Candidate. It should also be slightly quicker to implement however would require care, attention to detail and thorough testing due to the risk involved. Right now we are locked down so an application can only be edited by the candidate who made the application.

Hi @warrensearle I agree this needs more work.  Shall we chat next week so we can see what's possible and what we feel is safe and then I'll pass it back to the group to flesh out some ideas.  I would prefer that it's for the candidate to be in control.  This opens up an issue of re-opening applications at various stages to get the candidate to provide more information.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle this is not a huge priority. But can chat Wednesday about these requirements?

**Comment by warrensearle** [comment]
Sure @Rebecca-mcknight1991 lets arrange a time to review the requirements. I think this wednesday might be rather busy as 'the big' exercise is due to launch.

**Comment by KateMJAC** [comment]
To be reviewed as part of the May application and profile edit item on the RM.

**Comment by londonprojects** [comment]
Is this still blocked?

**Comment by londonprojects** [comment]
@KateMJAC
