### ISSUE TITLE
Add column sorting to table component

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/admin#541]

**Comment by warrensearle** [comment]
See #430 for more details

Update Table component so it supports column sorting.

Refer to [Column sort](https://moj-design-system.herokuapp.com/components/sortable-table) from MoJ design system

**Comment by crablab** [comment]
Hey @warrensearle :wave:  

I'm going to start working on this now. 

Just to confirm that this is okay to build directly into the table component? I think it might be a bit confusing otherwise :sweat_smile: 

At the moment we take the following props on the `table` component (example from ShortList.vue): 

```javascript
 <Table 
        data-key="id"
        :data="applicationRecords"
        :columns="[
          { title: 'Reference number' },
          { title: 'Name' },
          { title: 'Issues' },
          { title: 'Status' },
          { title: 'EMP' }
        ]"
        multi-select
        :selection.sync="selectedItems"
      >
```

I suggest we add an additional array element to the `columns` prop, eg: 
`{ title: 'Reference Number', sortable: true }`

This will be optional and default to `false` but when `set` to `true` will allow the column to be sortable. We'll need to do some state management within the component so we know which column is being sorted, and in which direction. 

The MoJ Design System doesn't have a way to clear the sort (except by refreshing the page I guess). This may be something we look at later, if it becomes an issue.

**Comment by warrensearle** [comment]
Have resurrected epic #430 so we can discuss and update the design of the Table component as a whole.
With regards sorting we'll need to define the database field(s) that each sortable column uses for its sort.
Let's start with one field per column (as future development we could consider multiple fields).

Would suggest something like the following for each sortable column:
`{ title: 'Reference Number', sortBy: 'referenceNumber' }`

and at the `Table` level we have a new event handler prop along the lines of:
```
    @sort='sortBy'
```
where the 'sort' event passes `field` and `direction` info
