### ISSUE TITLE
Correct number of assessments not showing in notifications

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#631]
**Describe the bug**
Only 100 pending emails showing on notifications when you send IAs. 

**To Reproduce**
1. Go to 00026
2. Click on send assessments
3. Send all
4. Click notifications
5. See list, copy to excel and see only 100 
6. Please make sure you have it in safe mode so the emails going to the assessors are only going to a shared inbox or try on a staging exercise

**Expected behavior**
It should show however many assessments you are sending, in this case 122.

**Comment by warrensearle** [comment]
Hey @Rebecca-mcknight1991 this is by design in that the page only shows up to 100 items in the queue... As the queue is processed, items from the top move across to Sent and new ones appear at the bottom.
We will be writing a paging component soon, so could look at using it here. Along with multi-select to enable Super Admins to delete/pause items from being sent out.

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle I thought that might be the case. The reason this became an issue was the team could not see that 122 emails were going to go before I hit start so they were nervous that some were missing. So if they just had a way to see exactly what is about to go out I think the issue would be resolved.

**Comment by crablab** [comment]
It might also be useful to just show at the top how many items there are in the queue :-)

**Comment by warrensearle** [comment]
That makes sense, thank you.
