### ISSUE TITLE
Stages lists:  Ability to see more than 50 candidates at a time

### ISSUE THREAD

**Issue by ClaireTroughtonJAC** [jac-uk/admin#636]
**Is your feature request related to a problem? Please describe.**
We have feedback from staff that it is difficult to update statuses when not all the candidates appear in the list.  The current view shows only 50 and until you update a status the other candidates do not appear.  

**Describe the solution you'd like**
I would either like a way of displaying all candidates or through the updating of statuses on each page with 50 on one page.  

**Describe alternatives you've considered**
Ultimately I want to sort columns and filter information - ie if you update 25 people to a passed status I can filter those by only showing those who had applied.  

**Additional context**

https://apply-admin.judicialappointments.digital/exercises/2k6Qo2JaesamXjhreHiq/stages/shortlisted

<img width="813" alt="Screenshot 2020-07-01 at 10 14 41" src="https://user-images.githubusercontent.com/27224574/86226553-bd581e00-bb83-11ea-8966-326b6808325e.png">

**Comment by ClaireTroughtonJAC** [comment]
Comment from user 

Can you please extend the list of 50 candidates that we can see on the platform to the full list of candidates selected for interview. I need to change the status of one candidate who has withdrawn due.

**Comment by crablab** [comment]
Just copying from my messages with @lloback: 

So for this one the 'easy' option seems to just be to increase the number of rows shown in the table. But that isn't a great option as it doesn't solve the underlying issue, doesn't scale and you end up with a huge page.
The better option would be to add some pagination on the table component, I think. 

We could take a parameter with the exerciseID in the Store to set the limit. Ideally we'd add a dropdown to set this limit on the frontend, but I think hardcoding it for now would be okay.

If you added forward/back buttons to the component you could then just adjust the indexes on the array that are shown, and skip forwards/back through said array. 

One thing to note is that we should make this change across all of the `stages` pages (Shortlisted, Selected, Review, Recommended, Handover) for consistency and because it will likely come up again anyway.

**Comment by enoranidi** [comment]
Agree with @crablab that we should not add more rows unless there are several users who have this same issue. 

If there is a user need then we could try to increase the number of table rows to say 100 (or whatever 'number' is reasonable from the users perspective).

I have a pagination example in my prototype, but here is a screenshot to show how the user can go back and forth:
<img width="1084" alt="Screenshot 2020-07-01 at 10 36 31" src="https://user-images.githubusercontent.com/1918282/86228806-c3033300-bb86-11ea-8695-cae695432cc3.png">

**Comment by warrensearle** [comment]
Whilst we are working on adding Pagination to the Table component I think we should remove the list size limit in Stages. This is a very quick change to make. For lots of data the UI will not be as efficient as we'd like but at least the team will be able to do what they need to.
Pagination will then follow as swiftly as possible via task #542

**Comment by warrensearle** [comment]
A hot fix has now been applied in version 0.15.1.
This ticket will therefore be closed and subsequent work on the table component carried out under #542
