### ISSUE TITLE
Spike: Select a method for sharing components between repositories or applications

### ISSUE THREAD

**Issue by lloback** [jac-uk/admin#640]
**Is your feature request related to a problem? Please describe.**
We have different vue applications. WE need to share components. This task is to make a decision of how we are going to share the components

**Describe the solution you'd like**
- NPM
- GIT
- other solution

**Describe alternatives you've considered**
At the end of this task we need to have a clear idea of how to share components.

**Comment by warrensearle** [comment]
Hey @tomlovesgithub please can you take a look at the approach outlined in the following article. It would appear to cover everything we could want. [Storybook](https://storybook.js.org) looks awesome and be great to use Github Packages (instead of npm):
https://medium.com/js-dojo/sharing-reusable-vue-js-components-with-lerna-storybook-and-npm-7dc33b38b011

**Comment by tomlovesgithub** [comment]
So we have managed to successfully publish a package of components to the Github package registry. 
[Reference tutorial](https://medium.com/js-dojo/sharing-reusable-vue-js-components-with-lerna-storybook-and-npm-7dc33b38b011)
This workflow may need to be refined and adapted for our final component package, however once the initial repo is set up adding/updating components should be straight forward.
Additional work can be done to handle versioning and automation of updates and publishing of the package, migrating tests over from the main repo will be a separate issue, as may also be installing the CSS design system's as dependancies.

- Before you begin install [lerna](https://lerna.js.org/) globally with `npm install --global lerna`, check for success with `lerna -v`.
- Initially, you can either set up a repo on GitHub and clone it to your local machine, or set up a local repo and attach a GitHub remote.
- Now initialise a lerna project within the folder `lerna init --independent` 
 - This generate a `/packages` directory, which will rename to `/components`.
 - We should also have a `lerna.json` file which should be changed to point to our `components/*` directory, rather than the `packages/*` repo
 - Also in `lerna.json` add `"command": {  
"publish": {  
"registry": "https://npm.pkg.github.com"  
}  
}`
- [create a public access token on github](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with **write:packages** and **read:packages;**, keep tab open or token to hand/clipboard
- Once the repo is set up, add a component/update within the `/components` directory, commit and push the update to GitHub.
  - When adding a component, be sure to store it in the `components` directory and ensure that `lerna.json` points to that directory.
  - Additionally ensure that components have an accompanying package.json in the directory with them, containing 
`{
  "name": "@your-username/this-component",  
   "version": "0.0.0",  
    "publishConfig": {  
      "access": "public"  
      }  
 },
 "repository": {
"type": "git",
"url": "ssh://git@github.com:your-username/this-repo.git"
}`
- log into the GitHub package registry from the command line with `npm login --registry=https://npm.pkg.github.com`
  - Username: Provide your GitHub username
  - Password: provide the public access token
  - Email: a valid email linked to your github account
 - if successful you will be given a message saying you have logged in.
 - run `lerna publish`
   - select version type (*patch, minor, major* *etc*)
   - confirm decision

 .... @todo finish me
.npmrc file for use of component library, install thru package.json rather than command line
