### ISSUE TITLE
QTs: Create new Countdown timer component

### ISSUE THREAD

**Issue by crablab** [jac-uk/admin#754]
This will be based on a design from Sean, but will be different from the component by Monika as it will clearly show the remaining time in digits to the user. 

It will probably take the following props:
- startTime (timestamp)
- duration (minutes)

It will then show the remaining time. 

Events should be emitted for: 
- 5 minutes remaining
- 1 minute remaining 
- end of time limit 

Wireframe and design coming soon.

**Comment by SeanHills** [comment]
![Desktop Timer.jpg](https://images.zenhubusercontent.com/5f2297b0b0a4c951a704a3e2/cbc4bce1-c781-491a-a81e-e38290a252cb)![Mobile 10 mins plus state.jpg](https://images.zenhubusercontent.com/5f2297b0b0a4c951a704a3e2/afaba34b-28ff-4c0e-a57c-d4a8641cedb0)![Mobile 10 mins remaining state.jpg](https://images.zenhubusercontent.com/5f2297b0b0a4c951a704a3e2/79fb1c41-24a6-4ae2-80fa-88e307b8d5ed)

Intended UX is for the timer to pin at the top of the screen so that it is always visible to the user.

It should transition at 10 minutes by changing colour as shown and being accompanied by the alert icon.

**Comment by lloback** [comment]
![image.png](https://images.zenhubusercontent.com/5eb93282d6984623e15443b7/363b7511-d01f-4e93-91ce-7e18e780a5d4)
