### ISSUE TITLE
Download scenario test responses 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/admin#989]
**Is your feature request related to a problem? Please describe.**
As an admin I need to be able to download the responses for scenario test so they can be marked. 

**Describe the solution you'd like**
XLSX download with names, emails, all answers to the questions

**Additional context**
Needed for 4 Nov

**Comment by warrensearle** [comment]
This includes names, reference numbers and all answers... but not email addresses. However closing this ticket as we will deal with email separately. We should encourage scores to be imported back into platform before emails are sent out, and ideally send emails via admin (rather than the current manual mail merge).
